"""refactor_locations_arrays_to_m2m

Revision ID: 10c3ad1a7fc9
Revises: 8b7c9d2e4f10
Create Date: 2026-07-29 18:07:06.839064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10c3ad1a7fc9'
down_revision: Union[str, Sequence[str], None] = '8b7c9d2e4f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_name'), 'levels', ['name'], unique=True)
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_styles_name'), 'styles', ['name'], unique=True)
    op.create_table('location_activities',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'activity_id')
    )
    op.create_table('location_levels',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'level_id')
    )
    op.create_table('location_styles',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'style_id')
    )

    # Миграция с PostgreSQL ARRAY на M2M-таблицы (location_activities, location_styles, location_levels)
    op.execute("""
        INSERT INTO activities (id)
        SELECT DISTINCT act_id
        FROM locations, UNNEST(activity_ids) AS act_id
        WHERE activity_ids IS NOT NULL AND array_length(activity_ids, 1) > 0
        ON CONFLICT (id) DO NOTHING;
    """)

    op.execute("""
        INSERT INTO styles (name)
        SELECT DISTINCT UNNEST(styles) FROM locations
        WHERE styles IS NOT NULL AND array_length(styles, 1) > 0
        ON CONFLICT DO NOTHING;
    """)

    op.execute("""
        INSERT INTO levels (name)
        SELECT DISTINCT UNNEST(levels) FROM locations
        WHERE levels IS NOT NULL AND array_length(levels, 1) > 0
        ON CONFLICT DO NOTHING;
    """)

    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('activities', 'id'), 
            COALESCE((SELECT MAX(id) FROM activities), 1)
        );
    """)

    op.execute("""
        INSERT INTO location_activities (location_id, activity_id)
        SELECT l.id, UNNEST(l.activity_ids)
        FROM locations l
        WHERE l.activity_ids IS NOT NULL AND array_length(l.activity_ids, 1) > 0
        ON CONFLICT DO NOTHING;
    """)

    op.execute("""
        INSERT INTO location_styles (location_id, style_id)
        SELECT l.id, s.id
        FROM locations l
        CROSS JOIN UNNEST(l.styles) AS elem_style
        JOIN styles s ON s.name = elem_style
        ON CONFLICT DO NOTHING;
    """)

    op.execute("""
        INSERT INTO location_levels (location_id, level_id)
        SELECT l.id, lev.id
        FROM locations l
        CROSS JOIN UNNEST(l.levels) AS elem_level
        JOIN levels lev ON lev.name = elem_level
        ON CONFLICT DO NOTHING;
    """)

    op.drop_index(op.f('ix_locations_activity_ids_gin'), table_name='locations', postgresql_using='gin')
    op.drop_index(op.f('ix_locations_levels_gin'), table_name='locations', postgresql_using='gin')
    op.drop_index(op.f('ix_locations_styles_gin'), table_name='locations', postgresql_using='gin')
    op.drop_column('locations', 'levels')
    op.drop_column('locations', 'activity_ids')
    op.drop_column('locations', 'styles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('styles', postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('locations',
        sa.Column('activity_ids', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text("'{}'::integer[]"),
        autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('levels', postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))

    op.execute("""
            UPDATE locations l
            SET activity_ids = COALESCE((
                SELECT array_agg(activity_id) FROM location_activities WHERE location_id = l.id
            ), '{}'::integer[]);

            UPDATE locations l
            SET styles = COALESCE((
                SELECT array_agg(s.name) FROM location_styles ls 
                JOIN styles s ON s.id = ls.style_id 
                WHERE ls.location_id = l.id
            ), '{}'::varchar[]);

            UPDATE locations l
            SET levels = COALESCE((
                SELECT array_agg(lev.name) FROM location_levels ll 
                JOIN levels lev ON lev.id = ll.level_id 
                WHERE ll.location_id = l.id
            ), '{}'::varchar[]);
        """)
    op.create_index(op.f('ix_locations_styles_gin'), 'locations', ['styles'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_locations_levels_gin'), 'locations', ['levels'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_locations_activity_ids_gin'), 'locations', ['activity_ids'], unique=False, postgresql_using='gin')
    op.drop_table('location_styles')
    op.drop_table('location_levels')
    op.drop_table('location_activities')
    op.drop_index(op.f('ix_styles_name'), table_name='styles')
    op.drop_table('styles')
    op.drop_index(op.f('ix_levels_name'), table_name='levels')
    op.drop_table('levels')
    op.drop_table('activities')
    # ### end Alembic commands ###
