"""add ondelete restrict to locations.city_id

Revision ID: 1b25bd9d2fc1
Revises: 360f4ac0bef1
Create Date: 2026-09-16 19:51:58.091512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b25bd9d2fc1'
down_revision: Union[str, Sequence[str], None] = '360f4ac0bef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('locations_city_id_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'cities', ['city_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_city_id_fkey'), 'locations', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
