"""create city, region, country

Revision ID: 46c0dfd261b2
Revises: b56b02cacf1f
Create Date: 2026-09-08 16:38:12.725440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c0dfd261b2'
down_revision: Union[str, Sequence[str], None] = 'b56b02cacf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country_id', name='uq_region_name_country')
    )
    op.create_index(op.f('ix_regions_country_id'), 'regions', ['country_id'], unique=False)
    op.create_table('cities',
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', name='uq_city_name_region')
    )
    op.create_index(op.f('ix_cities_region_id'), 'cities', ['region_id'], unique=False)
    op.add_column('locations', sa.Column('city_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_index(op.f('ix_locations_city_lower'), table_name='locations')
    op.drop_index(op.f('ix_locations_country_lower'), table_name='locations')
    op.drop_index(op.f('ix_locations_country_region_city'), table_name='locations')
    op.drop_index(op.f('ix_locations_region'), table_name='locations')
    op.drop_index(op.f('ix_locations_region_lower'), table_name='locations')
    op.create_index(op.f('ix_locations_city_id'), 'locations', ['city_id'], unique=False)
    op.create_foreign_key(None, 'locations', 'cities', ['city_id'], ['id'])
    op.drop_column('locations', 'city')
    op.drop_column('locations', 'region')
    op.drop_column('locations', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('country', sa.VARCHAR(length=120), server_default=sa.text("'Russia'::character varying"), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('region', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_index(op.f('ix_locations_city_id'), table_name='locations')
    op.create_index(op.f('ix_locations_region_lower'), 'locations', [sa.literal_column('lower(region::text)')], unique=False)
    op.create_index(op.f('ix_locations_region'), 'locations', ['region'], unique=False)
    op.create_index(op.f('ix_locations_country_region_city'), 'locations', ['country', 'region', 'city'], unique=False)
    op.create_index(op.f('ix_locations_country_lower'), 'locations', [sa.literal_column('lower(country::text)')], unique=False)
    op.create_index(op.f('ix_locations_city_lower'), 'locations', [sa.literal_column('lower(city::text)')], unique=False)
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=False)
    op.drop_column('locations', 'city_id')
    op.drop_index(op.f('ix_cities_region_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_regions_country_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_table('countries')
    # ### end Alembic commands ###
