"""init_location

Revision ID: 54fdb53e3676
Revises:
Create Date: 2026-02-27 16:54:08.373037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "54fdb53e3676"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "coordinates",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("has_overnight_stay", sa.Boolean(), nullable=False),
        sa.Column("has_food_service", sa.Boolean(), nullable=False),
        sa.Column("has_airport", sa.Boolean(), nullable=False),
        sa.Column("has_railway_station", sa.Boolean(), nullable=False),
        sa.Column("has_bus_station", sa.Boolean(), nullable=False),
        sa.Column(
            "available_activities",
            sa.Enum("hiking", "skiing", "swimming", name="activity_enum"),
            nullable=True,
        ),
        sa.Column("season_start_month", sa.Integer(), nullable=True),
        sa.Column("season_end_month", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location")
    # ### end Alembic commands ###
