"""remove favorite_locations

Revision ID: b56b02cacf1f
Revises: 9c1a2b3d4e5f
Create Date: 2026-09-03 16:42:46.122455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b56b02cacf1f'
down_revision: Union[str, Sequence[str], None] = '9c1a2b3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_locations_location_id'), table_name='favorite_locations')
    op.drop_index(op.f('ix_favorite_locations_user_id'), table_name='favorite_locations')
    op.drop_table('favorite_locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('favorite_locations_location_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_locations_pkey')),
    sa.UniqueConstraint('user_id', 'location_id', name=op.f('uq_favorite_locations_user_location'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_favorite_locations_user_id'), 'favorite_locations', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorite_locations_location_id'), 'favorite_locations', ['location_id'], unique=False)
    # ### end Alembic commands ###
