"""

Revision ID: f198bd16198d
Revises:
Create Date: 2026-04-13 17:49:07.721494

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f198bd16198d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column(
            "country",
            sa.String(length=120),
            server_default=sa.text("'Russia'"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("distance_to_city_km", sa.Integer(), nullable=True),
        sa.Column(
            "activity_ids",
            postgresql.ARRAY(sa.Integer()),
            server_default=sa.text("'{}'::integer[]"),
            nullable=False,
        ),
        sa.Column(
            "styles",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "levels",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_locations_city"), "locations", ["city"], unique=False)
    op.create_index(
        "ix_locations_country_region_city",
        "locations",
        ["country", "region", "city"],
        unique=False,
    )
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=False)
    op.create_index(op.f("ix_locations_region"), "locations", ["region"], unique=False)
    op.create_table(
        "favorite_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "location_id", name="uq_favorite_locations_user_location"
        ),
    )
    op.create_index(
        op.f("ix_favorite_locations_location_id"),
        "favorite_locations",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_locations_user_id"),
        "favorite_locations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_favorite_locations_user_id"), table_name="favorite_locations"
    )
    op.drop_index(
        op.f("ix_favorite_locations_location_id"), table_name="favorite_locations"
    )
    op.drop_table("favorite_locations")
    op.drop_index(op.f("ix_locations_region"), table_name="locations")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_index("ix_locations_country_region_city", table_name="locations")
    op.drop_index(op.f("ix_locations_city"), table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
